### PR TITLE
player-thumb: Fix fullscreen bugs

### LINKED ISSUE #7928: `player-thumb` "freezes" the project player in the editor
### Description

The `player-thumb` addon causes a peculiar bug that is triggered after going into and doing certain things in the editor, if you open a project to the project page. It makes the project's thumbnail continue to display even after it loads, effectively freezing the stage in a static image, until you go back to the project page, and then it doesn't happen again.

### Steps to reproduce

1. Visit a project page with the addon enabled.
2. Click the green flag, or don't.
3. Enter the editor by clicking "See inside".
4. I don't know exactly what triggers it, and sometimes it happens automatically, but click some buttons, hide/show sprites, add sprites, etc. until you see the project's thumbnail appear over the stage.

The project's thumbnail will cover the stage.

5. Click "See Project Page" and things will return to normal.

### Demonstration(s) and additional context

_No response_

### Environment

Browser: Edge 130
Scratch Addons version: 4e04de021e6eeb02fa91f724c02770d0f4b5de90
Operating system: Windows

### LINKED ISSUE #8027: player-thumb breaks in fullscreen when thumbnail is not 4:3
### Description

When using the thumbnail setter to set a thumbnail that is not 4:3, it is not displayed correctly by `player-thumb` in fullscreen

### Steps to reproduce

1. Set a wide thumbnail with `animated-thumb`
2. Enable `player-thumb`
3. Open the project in fullscreen
4. Reload the page

### Demonstration(s) and additional context

A screenshot from the discord server:

### Environment

Browser: Chromium 131
Scratch Addons version: 1.40.0
Operating system: Linux

### LINKED ISSUE #8033: Show project thumbnail while loading blocks the project controls when loaded after the project has already loaded
### Description

When this addon loads after the project has already loaded and started, the project controls get blocked and the project replaced with a thumbnail, making the project unusable.

This happens pretty much every time a project is loaded that doesn't have too many blocks, because SA has begun loading really slowly recently in general

### Steps to reproduce

Wait for a project to load and start it before SA has loaded. Once SA loads, the project will become unusable.
This doesn't happen when dynamically enabling the addon

### Demonstration(s) and additional context

image

### Environment

Browser: Edge 131
Scratch Addons version: 1.40.0
Operating system: Windows

### PR DESCRIPTION
**Pull request by Samq64**
Resolves #8027
Resolves #8033
Properly fixes #7928

### Changes

Removes the event listener instead of hiding the thumbnail in the editor and fixes enhanced fullscreen compatibility.

### Reason for changes

To fix bugs such as one from feedback where the thumbnail gets stuck when going fullscreen from the editor.

### Tests

Tested on Chromium.

### CODE REVIEW

**Comment by Samq64** [comment]
Currently the blue loader background's styles are applied `fullscreen` even when `player-thumb` is disabled. I tried adding a class to the loader but it gets removed when switching player modes.

File: addons/player-thumb/userscript.js [hunk 1]
```diff
@@ -7,18 +7,25 @@ export default async function ({ addon, console }) {
   thumb.classList = "sa-project-thumb loading";
 
   const stageWrapper = await addon.tab.waitForElement('div[class*="stage-wrapper_stage-wrapper_"]');
+  addon.tab.redux.initialize();
+
+  // It's possible this runs after the project loads even without dynamic enable
+  if (addon.tab.redux.state?.scratchGui?.vmStatus?.started) return;
```
Comment (mxmou) [inline addons/player-thumb/userscript.js:13]:
```suggestion
  if (addon.tab.redux.state?.scratchGui?.projectState?.loadingState === "SHOWING_WITH_ID") return;
```
`vmStatus.started` is false if the project has been loaded but the green flag hasn't been clicked. To test this, you can add `await new Promise(resolve => setTimeout(resolve, 3000));` to the beginning of the userscript.

**Review by mxmou — APPROVED** [review]
