### PR TITLE
Fix `discuss-button` duplicating username when changing settings

### LINKED ISSUE #6057: Changing `discuss-button` settings with compact navbar on duplicates username
### Description

If you modify the links in the navigation bar in any way using the `discuss-button` feature enabled and you have the compact navbar setting enabled, then the username in the dropdown duplicates.

### Steps to reproduce

1. Enable `discuss-button` and the compact navbar
2. Open a Scratch tab and open the dropdown
3. Make changes to the links in the SA settings

### Demonstration(s) and additional context

https://discord.com/channels/806602307750985799/1107703718033490020

### Environment

Browser: Chrome 113
Scratch Addons version: v1.32.0-pre
Operating system: MacOS

### PR DESCRIPTION
**Pull request by rgantzos**
Resolves #6057

### Changes

Checks for the existing username element before making one

### Reason for changes

To fix a bug

### Tests

I tested in Chrome 113 with SA v1.32.0-prerelease

### CODE REVIEW

File: addons/discuss-button/r2.js [hunk 1]
```diff
@@ -9,9 +9,11 @@ export default async function ({ addon }) {
       const dropdown = await addon.tab.waitForElement(".dropdown-menu .user-nav");
       (await addon.tab.waitForElement(".user-icon")).classList.add("sa-compact-profile-icon");
       const profileSpans = dropdown.childNodes[0].childNodes[0];
-      span = profileSpans.appendChild(document.createElement("span"));
-      span.className = "sa-profile-name";
-      span.textContent = username;
+      if (!document.querySelector(".sa-profile-name")) {
```
Comment (mxmou) [inline addons/discuss-button/r2.js:12]: This userscript doesn't have the bug - it already checks if the element exists (`if (!span && ...)` on line 6).

File: addons/discuss-button/www.js [hunk 2]
```diff
@@ -11,9 +11,11 @@ export default async function ({ addon }) {
         return;
       }
       const profileSpans = dropdown.childNodes[0].childNodes[0];
-      span = profileSpans.appendChild(document.createElement("span"));
-      span.className = "sa-profile-name";
-      span.textContent = username;
+      if (!document.querySelector(".sa-profile-name")) {
```
Comment (mxmou) [inline addons/discuss-button/www.js:14]:
```suggestion
      if (!span) {
```

**Review by DNin01 — APPROVED** [review]
