### PR TITLE
Fix "collapse when mouse leaves sprite panel" bug (sprite-properties)

### LINKED ISSUE #5898: sprite-properties: "collapse when mouse leaves sprite panel" not working properly
### Description

> the panel closes when you go on pop-up elements

### Steps to reproduce

See video.
Make sure setting `AUTOMATICALLY COLLAPSE WHEN MOUSE LEAVES SPRITE PANEL` is enabled.

https://user-images.githubusercontent.com/17484114/230694271-784ad36a-6d3a-48a2-a409-8fce24a056ae.mp4

### Demonstration(s) and additional context

None

### Environment

Bug has been around since this addon was released AFAIK

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves #5898

### Changes

The sprite properties won't hide if the mouse left them as a result of the user changing the direction of a sprite by dragging the dial.
The sprite properties will stay visible until the cursor leaves the sprite properties again (excluding the direction dial). I don't think it makes sense to try to do better in this case.

### Reason for changes

Fixes an important bug.

### Tests

Tested in Chromium in scratch.mit.edu and https://scratchfoundation.github.io/scratch-gui/beta/

### CODE REVIEW

File: addons/sprite-properties/userscript.js [hunk 1]
```diff
@@ -35,12 +35,14 @@ export default async function ({ addon, console, msg }) {
       setPropertiesPanelVisible(false);
     }
   }
+  const isDirectionPopoverOpen = () =>
+    document.querySelector("body > div.Popover > div > div > [class*=direction-picker_button-row_]");
   // Close properties panel when mouse leaves the entire sprite panel
   document.body.addEventListener(
     "mouseleave",
     (e) => {
       if (e.target.matches('[class*="sprite-selector_sprite-selector_2KgCX"]')) {
```
Comment (WorldLanguages) [inline addons/sprite-properties/userscript.js:44]: https://github.com/ScratchAddons/ScratchAddons/pull/5473#pullrequestreview-1440218506

**Review by apple502j — APPROVED** [review]
