### PR TITLE
infinite-scroll: Fix donor text with "fix footer"

### LINKED ISSUE #1600: Footer part missing if fixed footer
For the "fix footer" in "infinite scrolling" it doesn't show this part at the bottom.
image

*Note: This is because the bottom text is a different div than the footer.

### PR DESCRIPTION
**Pull request by CST1229**
Resolves #1600

### Changes

In the `infintie-scroll` addon, this adds a simple userscript for the home page that simply moves the donor text (the "Scratch is available for free..." text) into the footer, allowing it to show when the footer is hovered over instead of being at the bottom of the page.
This also adds a CSS variable for the hovered footer's height so that the userscript can change it to make the text visible once it runs.

### Reason for changes

Not having the donor text be with the footer just looks weird.

### Tests

Seems to work.
pic
The donor text script moves the text about 1-2 secs after the footer style loads which is okay.

### CODE REVIEW

File: addons/infinite-scroll/moveDonor.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+export default async function ({ addon, global, console }) {
```
Comment (FunctionalMetatable) [inline addons/infinite-scroll/moveDonor.js:1]:
```suggestion
export default async function ({ addon, global, console }) {
```
