### PR TITLE
custom-block-shape: fix dropdown arrow position

### LINKED ISSUE #6692: Block dropdown arrows are positioned incorrectly after dynamically disabling or reconfiguring `custom-block-shape`
### Description

https://github.com/ScratchAddons/ScratchAddons/assets/106490990/6a426672-1548-4142-9f17-87bf1f2af99e

How much it's offset depends on your settings.

This seems to persist until you reload. If I were to guess, I'd think something is only being changed the first time you run the addon, not on dynamic disables or setting changes.

### Steps to reproduce

1. Open the editor.
2. Enable `custom-block-shape`
3. Adjust the padding size, or if it has already been changed, disable the addon.

### Demonstration(s) and additional context

_No response_

### Environment

Browser: Edge 117
Scratch Addons version: https://github.com/ScratchAddons/ScratchAddons/commit/79fc955912e7c0359a6bb5aa4f8baeb7790d9eab
Operating system: Windows 11

### PR DESCRIPTION
**Pull request by mxmou**
Resolves #6692

### Changes

* Moves a variable declaration to fix #6692
* Changes how the arrow position is calculated - now it's actually centered even if the padding isn't 100%.

### Tests

Tested on Edge and Firefox.

### CODE REVIEW

File: addons/custom-block-shape/userscript.js [hunk 1]
```diff
@@ -157,9 +158,9 @@ export default async function ({ addon, console }) {
       BlockSvg.SHAPE_IN_SHAPE_PADDING[1][2] = 5 * GRID_UNIT * multiplier;
       BlockSvg.SHAPE_IN_SHAPE_PADDING[1][3] = 5 * GRID_UNIT * multiplier;
 
-      var originalDropdownObject = BlocklyInstance.FieldDropdown.prototype.positionArrow;
       BlocklyInstance.FieldDropdown.prototype.positionArrow = function (x) {
-        this.arrowY_ = 11 * multiplier;
+        const arrowHeight = 12;
+        this.arrowY_ = (BlockSvg.FIELD_HEIGHT - arrowHeight) / 2 + 1;
```
Comment (WorldLanguages) [inline addons/custom-block-shape/userscript.js:163]: No problem if `BlockSvg.FIELD_HEIGHT - arrowHeight` is not even, right? It might end up being a decimal

**Review by WorldLanguages — APPROVED** [review]

File: addons/custom-block-shape/userscript.js (hunk 1 above)
Comment (mxmou) [reply addons/custom-block-shape/userscript.js:163]: This value is used to set the element's `transform`, so decimals are fine.
