### PR TITLE
hide-project-stats: fix padding, show own stats option, My Stuff support

### LINKED ISSUE #3374: Show stats on your own projects
# Problem

I recently enabled the hide project stats addon. And though, yes, I do love to not know how many loves and faves a generic platformer has, I still want to know how many my own project does.

# Solution

Even though it's someone's own project, they still might want to hide some stats, like the remix count. So, it would be best to use the options already there for other people's projects, and add more options for the user's own.

## Alternatives

An alternative would be to just add a checkbox named something like "Still show stats on your own projects".

### LINKED ISSUE #3376: Hide project stats: Placement of buttons differs on different projects
# Description

The spacing between the love and favourite buttons differs on different projects.

# Repoduction steps

1. Apply the settings json file at the bottom.
2. Go to the first project in the Recent section of the [Explore](https://scratch.mit.edu/explore/projects/all/recent) tab.
3. Go to the most loved and faved project (aka [Paper Minecraft](https://scratch.mit.edu/projects/10128407/)).
4. Compare the spacing between the love and favourite buttons and the view count of both projects.

# Expectation

The love and fave buttons, and the remix and view counts (if enabled) should all be right next to each other.

# Reality

The spacing between the buttons is completely different on different projects.
I believe this is because the spacing between them remains the same as if the love and fave counts were still visible - which is futher proved by the fact that Paper Minecraft has way more spacing than any other project, and the most recently shared project (found in the Recent section of the Explore tab) does not have much.

# Screenshots

image
image

Taken from the first two projects I saw, [Goodnight Bubbles](https://scratch.mit.edu/projects/421256352/) and [Honeybee True or False](https://scratch.mit.edu/projects/562423200/) respectively.

# Environment

- Browser: Microsoft Edge Beta 93.0.961.27
- Scratch Addons version: v1.19.1
- Operating system: Windows 10 21H1 build 19041
- Settings JSON:
```JSON
{"core":{"lightTheme":false,"version":"1.19.1"},"addons":{"2d-color-picker":{"enabled":true,"settings":{}},"60fps":{"enabled":true,"settings":{"framerate":60}},"account-settings-capitalize":{"enabled":true,"settings":{}},"animated-thumb":{"enabled":false,"settings":{"persistentThumb":false}},"better-emojis":{"enabled":false,"settings":{}},"better-featured-project":{"enabled":true,"settings":{"blur":0}},"better-img-uploads":{"enabled":true,"settings":{"fitting":"fit"}},"better-quoter":{"enabled":false,"settings":{}},"bitmap-copy":{"enabled":true,"settings":{}},"block-palette-icons":{"enabled":true,"settings":{}},"block-switching":{"enabled":true,"settings":{"border":true,"control":true,"customargs":true,"customargsmode":"defOnly","data":true,"event":true,"extension":true,"looks":true,"motion":true,"noop":true,"operator":true,"sensing":true,"sound":true}},"blocks2image":{"enabled":true,"settings":{}},"cat-blocks":{"enabled":true,"settings":{"watch":false}},"clones":{"enabled":true,"settings":{}},"cloud-games":{"enabled":false,"settings":{}},"color-picker":{"enabled":true,"settings":{}},"comments-linebreaks":{"enabled":true,"settings":{}},"compact-messages":{"enabled":false,"settings":{"comment_padding":5,"hide_icons":false,"message_padding":5}},"confirm-actions":{"enabled":true,"settings":{"closingtopic":true,"followinguser":false,"joiningstudio":false,"projectsharing":true}},"copy-message-link":{"enabled":true,"settings":{}},"ctrl-click-run-scripts":{"enabled":false,"settings":{}},"ctrl-enter-post":{"enabled":true,"settings":{"comments":true,"forums":false}},"curator-link":{"enabled":true,"settings":{"styleAsNormalText":true}},"custom-block-shape":{"enabled":false,"settings":{"cornerSize":200,"notchSize":100,"paddingSize":100}},"custom-zoom":{"enabled":true,"settings":{"autohide":true,"maxZoom":500,"minZoom":40,"speed":"short","startZoom":68,"zoomSpeed":50}},"customize-avatar-border":{"enabled":false,"settings":{"fill-transparent":false,"hide-outline":false,"outline-color":"#4d97ff40"}},"dango-rain":{"enabled":false,"settings":{}},"dark-www":{"enabled":true,"settings":{"selectedMode":"experimental-dark"}},"data-category-tweaks-v2":{"enabled":true,"settings":{"moveReportersDown":true,"separateListCategory":true,"separateLocalVariables":true}},"debugger":{"enabled":true,"settings":{}},"default-project":{"enabled":true,"settings":{"projectId":558275622}},"disable-auto-save":{"enabled":false,"settings":{}},"disable-stage-drag-select":{"enabled":true,"settings":{}},"discuss-button":{"enabled":true,"settings":{"buttonName":"Discuss","removeIdeasBtn":true}},"drag-drop":{"enabled":true,"settings":{"use-hd-upload":true}},"editor-colored-context-menus":{"enabled":true,"settings":{}},"editor-dark-mode":{"enabled":true,"settings":{"accent":"#151515","activeTab":"#202020","affectPaper":true,"affectStage":true,"border":"#ffffff0d","categoryMenu":"#202020","darkComments":false,"darkScrollbars":true,"dots":true,"fullscreen":"#000000","highlightText":"#4d97ff","input":"#202020","menuBar":"#4d97ff","page":"#111111","palette":"#202020","primary":"#4d97ff","selectedMode":"3-darker","selector":"#202020","selector2":"#202020","selectorSelection":"#111111","stageHeader":"#000000","tab":"#151515","textShadow":false,"workspace":"#151515"}},"editor-devtools":{"enabled":true,"settings":{"enableCleanUpPlus":true,"enableMiddleClickFinder":true,"enablePasteBlocksAtMouse":true}},"editor-messages":{"enabled":true,"settings":{}},"editor-searchable-dropdowns":{"enabled":true,"settings":{}},"editor-sounds":{"enabled":true,"settings":{}},"editor-stage-left":{"enabled":false,"settings":{}},"editor-stepping":{"enabled":true,"settings":{"highlight-color":"#0000ff"}},"editor-theme3":{"enabled":true,"settings":{"Pen-color":"#0FBD8C","control-color":"#FFAB19","custom-color":"#5f49d8","data-color":"#FF8C1A","data-lists-color":"#FF661A","events-color":"#FFBF00","input-color":"#202020","looks-color":"#9966FF","motion-color":"#4C97FF","operators-color":"#59C059","sa-color":"#29BEB8","sensing-color":"#5CB1D6","sounds-color":"#CF63CF","text":"colorOnBlack"}},"exact-count":{"enabled":true,"settings":{"forumuser":true,"studio":true,"user":true}},"expanding-search-bar":{"enabled":true,"settings":{}},"feature-unshared":{"enabled":true,"settings":{}},"fix-pasted-scripts":{"enabled":true,"settings":{}},"fix-uploaded-svgs":{"enabled":true,"settings":{}},"folders":{"enabled":true,"settings":{}},"forum-copy-code":{"enabled":true,"settings":{}},"forum-quote-code-beautifier":{"enabled":true,"settings":{"bordercolor":"#28A5DA"}},"forum-search":{"enabled":true,"settings":{}},"forum-time-zones":{"enabled":true,"settings":{}},"forum-toolbar":{"enabled":true,"settings":{"center":true,"code":true,"color":true,"dictionary":false,"google":false,"wiki":true,"wp":true}},"full-signature":{"enabled":true,"settings":{"blocks":true,"signature":true,"whathappen":true,"whatworkingon":true}},"gamepad":{"enabled":true,"settings":{"hide":true}},"hide-delete-button":{"enabled":true,"settings":{"costumes":true,"sounds":true,"sprites":true}},"hide-flyout":{"enabled":true,"settings":{"speed":"short","toggle":"cathover"}},"hide-project-stats":{"enabled":true,"settings":{"favorites":true,"loves":true,"lovesFront":true,"remixes":true,"remixesFront":true,"views":false}},"image-uploader":{"enabled":true,"settings":{"project_thumbnails":false}},"infinite-scroll":{"enabled":true,"settings":{"forumScroll":true,"messageScroll":true,"profileCommentScroll":true,"projectScroll":true,"showFooter":false,"studioActivityScroll":true,"studioBrowseProjectScroll":true,"studioCuratorScroll":true,"studioProjectScroll":true,"studioScroll":true}},"initialise-sprite-position":{"enabled":true,"settings":{"library":false,"x":0,"y":0}},"items-per-row":{"enabled":false,"settings":{"projects":5,"search":4,"studioCurators":3,"studioProjects":3,"studios":4,"users":11}},"last-edit-tooltip":{"enabled":true,"settings":{}},"live-featured-project":{"enabled":true,"settings":{"alternativePlayer":"forkphorus","autoPlay":true,"enableTWAddons":true,"forceAlternative":true,"showMenu":false}},"load-extensions":{"enabled":true,"settings":{"music":false,"pen":true,"text2speech":false,"translate":false,"videoSensing":false}},"longer-wiwo":{"enabled":true,"settings":{}},"material-forum-editor-buttons":{"enabled":true,"settings":{}},"mediarecorder":{"enabled":true,"settings":{}},"message-filters":{"enabled":true,"settings":{}},"more-links":{"enabled":true,"settings":{}},"mouse-pos":{"enabled":true,"settings":{}},"msg-count-badge":{"enabled":false,"settings":{"color":"#175ef8","showOffline":true}},"mute-project":{"enabled":true,"settings":{}},"my-ocular":{"enabled":true,"settings":{"discuss":true,"profile":true,"reactions":true}},"name-backpack-items":{"enabled":true,"settings":{}},"no-script-bumping":{"enabled":true,"settings":{}},"old-studio-layout":{"enabled":false,"settings":{"version":"scratchr2"}},"onion-skinning":{"enabled":false,"settings":{"afterTint":"#0000FF","beforeTint":"#FF0000","default":false,"layering":"front","mode":"tint","next":0,"opacity":25,"opacityStep":10,"previous":1}},"paint-by-default":{"enabled":true,"settings":{"backdrop":"paint","costume":"upload","sound":"upload","sprite":"paint"}},"pause":{"enabled":true,"settings":{}},"progress-bar":{"enabled":true,"settings":{"height":5,"topbar":true}},"project-info":{"enabled":true,"settings":{"editorCount":true}},"project-notes-tabs":{"enabled":false,"settings":{}},"redirect-mobile-forums":{"enabled":true,"settings":{}},"remix-tree-button":{"enabled":true,"settings":{"buttonColor":"#4d97ff"}},"remove-curved-stage-border":{"enabled":true,"settings":{}},"remove-sprite-confirm":{"enabled":false,"settings":{}},"resizable-comment-input":{"enabled":false,"settings":{}},"scratch-messaging":{"enabled":false,"settings":{}},"scratch-notifier":{"enabled":true,"settings":{"becomeownerstudio_notifications":true,"commentsforme_notifications":true,"commentsonmyprojects_notifications":true,"curatorinvite_notifications":true,"favoriteproject_notifications":true,"followuser_notifications":true,"forumpost_notifications":true,"loveproject_notifications":true,"mark_as_read_when_clicked":true,"notification_sound":"system-default","remixproject_notifications":true,"studioactivity_notifications":false}},"scratchblocks":{"enabled":true,"settings":{}},"scratchr2":{"enabled":true,"settings":{"activeColor":"#4280d7","linkColor":"#4d97ff","primaryColor":"#4d97ff"}},"scratchstats":{"enabled":true,"settings":{}},"search-profile":{"enabled":true,"settings":{}},"semicolon":{"enabled":false,"settings":{}},"show-bbcode":{"enabled":true,"settings":{}},"studio-followers":{"enabled":true,"settings":{}},"studio-tools":{"enabled":true,"settings":{"mystufftools":true}},"transparent-orphans":{"enabled":true,"settings":{"block":2,"dragged":15,"orphan":50}},"true-youtube-links":{"enabled":true,"settings":{}},"turbowarp-player":{"enabled":true,"settings":{"action":"player","addons":true}},"user-id":{"enabled":true,"settings":{}},"variable-manager":{"enabled":true,"settings":{}},"youtube-fullscreen":{"enabled":true,"settings":{}}}}
```

### PR DESCRIPTION
**Pull request by lisa-wolfgang**
Resolves #3376
Resolves #3374

### Changes

The padding between the buttons when the labels are hidden has been adjusted to match the appearance of vanilla Scratch.

image

It is now also possible to show statistics on the project page when the user owns the project they're viewing:

image

When the user is signed out, and the love and favorite counts are set to be hidden, the love and favorite buttons won't appear at all.

In addition, the addon now also supports the My Stuff page. If "show stats on my own projects" is enabled, all statistics will show in My Stuff, since they are all projects owned by the user. As the comment count and (broken) studio count for a project is viewable in My Stuff, new settings for these have also been added.

image

### Reason for changes

The new appearance of the love and favorite buttons is much improved from the existing version, which has inconsistent spacing depending on the love/favorite counts.
Also, users may still want to be able to see stats on their own projects without having to disable and reenable the addon.
In addition, for a truly comprehensive project statistic hiding experience, the user would also want the stats on the My Stuff page to be hideable as well.

### Tests

Tested to work on Chromium 106 and Firefox 105.0.3.

### Known issues
None currently.

### CODE REVIEW

File: addons/hide-project-stats/userscript.js [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+  function refreshLabels() {
+    refreshButton(loves);
+    refreshButton(favorites);
+    // If the user has the "show stats on my own projects" setting enabled,
+    // show the remix and view count if the user owns the project.
+    // Love and favorite counts are handled separately since they get custom labels.
+    document.querySelectorAll(".project-remixes, .project-views").forEach((element) => {
+      if (!addon.self.disabled && addon.settings.get("showOwnStats") && visitingOwnProject) {
+        element.style = "display: flex;";
```
Comment (FunctionalMetatable) [inline addons/hide-project-stats/userscript.js:22]: use element.style.display

Comment (lisa-wolfgang) [reply addons/hide-project-stats/userscript.js:22]: Are you sure that works? Last I checked, doing it that way is depreciated...

Comment (apple502j) [reply addons/hide-project-stats/userscript.js:22]: Add a class and use userstyle.

Comment (WorldLanguages) [reply addons/hide-project-stats/userscript.js]: `element.style.display = "flex"` and `element.style = "display: flex;"` are equivalent (well, and the second one is worse, because it removes any existing inline styles)

**Comment by WorldLanguages** [comment]
With `SHOW STATS ON MY OWN PROJECTS` enabled, after loving my own project, class `stat-display` is not readded and the love count is gone.
Code is hard to read so I attempted to fix it and failed lol
This PR is low prio because few people actually use this addon, as far as we know

File: addons/hide-project-stats/userscript.js [hunk 2]
```diff
@@ -2,22 +2,25 @@ export default async function ({ addon, global, console, msg, safeMsg: m }) {
   let loves = { name: "love" };
   let favorites = { name: "favorite" };
   let username = await addon.auth.fetchUsername();
+  let visitingOwnProject = username !== null && document.querySelector(".button.action-button.report-button") === null;
```
Comment (WorldLanguages) [inline addons/hide-project-stats/userscript.js:5]: Project might have loaded yet. So report button might not exist yet for a project made by someone else.

**Comment by lisa-wolfgang** [comment]
@WorldLanguages Let me know if you can still repro the `SHOW STATS ON MY OWN PROJECTS` bug.

File: addons/hide-project-stats/userscript.js [hunk 3]
```diff
@@ -0,0 +1,107 @@
+export default async function ({ addon, global, console, msg, safeMsg: m }) {
+  let loves = { name: "love" };
+  let favorites = { name: "favorite" };
+  let username = await addon.auth.fetchUsername();
+  await addon.tab.waitForElement(".button.action-button.report-button", { markAsSeen: true });
```
Comment (WorldLanguages) [inline addons/hide-project-stats/userscript.js:5]: Don't mark it as seen on here

**Comment by WorldLanguages** [comment]
Bug? Page loaded like this, "show own stats" enabled

image

Going inside then outside:
image

**Comment by WorldLanguages** [comment]
Oh boy, it still randomly breaks...
image

**Comment by lisa-wolfgang** [comment]
I think I've figured out the cause of the unreliability.

In order to handle the love and favorite buttons, a MutationObserver is created. Whenever the classes are changed (by clicking the buttons) the class that unhides the labels is *supposed to* be reapplied. However, there's a nasty race condition between the placement of the MutationObserver and Scratch replacing the entire container element, perhaps to update some set of values. If the refresh occurs before the MutationObserver gets hooked, all is well, but if the refresh occurs after the MutationObserver gets hooked, the MutationObserver hook is cleared and therefore cannot act on the refresh, resulting in the labels staying hidden in scenarios when we want them to show. We can't simply start with the labels showing and then apply a class to hide them because then we would have the same problem in reverse. I'm not sure if there's a good way to address this.

**Comment by lisa-wolfgang** [comment]
I realized that I could easily resolve this issue by moving the `stat-display` class to the parent of the stats row, which Scratch doesn't touch once loaded.

**Comment by lisa-wolfgang** [comment]
All reported bugs should now be fixed. I've changed the userscript to be a lot more robust against the changing dynamics of the project page, and the methodology is less sketchy as a bonus.

**Review by WorldLanguages — APPROVED** [review]
Nice job fixing the race condition! The code is simpler too

**Comment by WorldLanguages** [comment]
@lisa-wolfgang Question: do old users of this addon, expect My Stuff to be affected? Is it worth it to make this togglable?
Unless I'm missing something, all users of this addon will see their project stats on My Stuff hidden after the update, unless they enable one of the new settings.

**Comment by WorldLanguages** [comment]
Needs 1 more approval, but **please don't merge** until we reach a conclusion about what I said in the above comment.

**Review by apple502j — CHANGES_REQUESTED** [review]
That's how you use this :)

**Comment by WorldLanguages** [comment]
I'm not "requesting changes" - I'm asking the PR author if a specific situation, which would only affect a minority of users, was taken into account :P
But yeah fine, that's the simplest way to block the PR from getting merged accidentally

**Comment by lisa-wolfgang** [comment]
That's a good point -- it's not a good idea to automatically enable new functionality for existing users. Then again, this is a relatively minor change that most users of the addon would probably welcome. If they don't want to see the stats on their projects, they probably don't want to see the stats in My Stuff either. Another option, like you said, is to add a setting for My Stuff. This would probably be enabled by default for new users (migration code would be needed for existing users) and it could only appear when "show stats on my own projects" is enabled, which would also be by default.

**Comment by WorldLanguages** [comment]
IMO, whether this addon affects My Stuff should be a setting, off by default, off for existing users, no need for migration.
But as I'm not a user of this addon, I can't say for sure. But my intuition says hiding stats in project pages and hiding them on My Stuff sound like 2 separate features that I should be able to toggle separately.

**Comment by lisa-wolfgang** [comment]
I'm just concerned that a separate setting for My Stuff will cause extra confusion given the behavior of "show stats on my own projects." What happens if the user shows stats on their own projects but hides stats in My Stuff?

**Comment by lisa-wolfgang** [comment]
World_Languages and I decided to rename the current setting to "show stats on my own project pages" and add a new setting for My Stuff specifically.

**Review by WorldLanguages — DISMISSED** [review]

File: addons/hide-project-stats/userscript.js [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+  let favorites = { name: "favorite" };
+
+  /**
+   * Checks whether or not the currently signed-in user matches the project owner.
+   * @returns A boolean value.
+   */
+  async function isVisitingOwnProject() {
+    let username = await addon.auth.fetchUsername();
+    await addon.tab.waitForElement(".title");
+    return username !== null && document.querySelector(".title form");
```
Comment (RedGuy12) [inline addons/hide-project-stats/userscript.js:12]:
```suggest
    let username = await addon.auth.fetchUsername();
    if (!username) return false
    return !!await addon.tab.waitForElement(".title form");
 ```

Comment (WorldLanguages) [reply addons/hide-project-stats/userscript.js:12]: confusing, waitForElement will never resolve to a falsey value

**Review by WorldLanguages — APPROVED** [review]

**Comment by lisa-wolfgang** [comment]
Tested on Firefox 105.0.3; no issues found.
