### PR TITLE
Calculate stepSize

### LINKED ISSUE #2362: Decimals in Followers over time
**Describe the bug**

**To Reproduce**

1. Go to someone's profile who has had the same amount of followers for a while, example S1A_02: https://scratch.mit.edu/users/S1A_02/
3. Scroll down to 'Followers over time'
4. See decimals

**Expected behavior**

have decimals

**Screenshots**

deciglitch

**Device (please complete the following information):**
- OS: Windows
- Browser Google Chrome
- Version version of what?

**Additional context**

no

### PR DESCRIPTION
**Pull request by apple502j**
Resolves #2362 
Math is fun.

### CODE REVIEW

File: addons/scratchstats/userscript.js [hunk 1]
```diff
@@ -85,6 +85,10 @@ export default async function ({ addon, msg, console }) {
           canvasContainer.style.height = "400px";
           const canvas = document.createElement("canvas");
           canvasContainer.appendChild(canvas);
+          const stepAvg = historyData.reduce((acc, cur) => acc + cur.value / historyData.length, 0);
+          const stepLog = Math.log10(stepAvg);
+          const stepSize = Math.pow(10, Math.max(Math.round(stepLog) - 1, 1));
+          console.log(stepLog, stepSize);
```
Comment (TheColaber) [inline addons/scratchstats/userscript.js:91]: remove this prob

**Review by WorldLanguages — APPROVED** [review]

**Comment by WorldLanguages** [comment]
Doesn't chartjs lib have a better way to do this tho?

**Comment by apple502j** [comment]
Well another reason we should bump it to v3 :P
