### PR TITLE
`blocks2image`: fix multiple reqs for same image

### LINKED ISSUE #7681: `blocks2image`: up to 10x worse performance without `editor-theme3`
### Description

Without `editor-theme3` enabled `blocks2image` can take up to 10 times longer to export images compared to when it is enabled. Normally that isn't a big deal but it can add up when exporting 100+ blocks.

### Steps to reproduce

1. Enable `blocks2image` and disable `editor-theme3`
2. Open [Paper Minecraft](https://scratch.mit.edu/projects/10128407/editor/)
3. Switch to the "Steve Arm" sprite
4. Export all blocks as an image
5. Enable `editor-theme3`
6. Export the blocks again

### Demonstration(s) and additional context

https://github.com/ScratchAddons/ScratchAddons/pull/6830#issuecomment-2248706640:

> > The steve arm sprite takes about 400ms (edit: 250ms) for me to load the preview
> 
> Do you happen to have `editor-theme3` enabled? For me it seems to significantly improve the performance for whatever reason.
> 
> 

### Environment

Browser: Chromium 126
Scratch Addons version: 1.38.4
Operating system: Linux

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves #7681

### Changes

Identical image URLs are only fetched once.

I used the new(ish) `Object.groupBy()` function to group icons by their image URLs.

I added logs when exporting blocks as image to facilitate testing this PR. See #7681 for repro steps and an example project and sprite. These logs will be removed before merging.

### Tests

Tested in Chromium.

Make sure that `editor-theme3` is off when testing this. If it is on, everything will be a data: url anyway.

### CODE REVIEW

File: addons/blocks2image/userscript.js [hunk 1]
```diff
@@ -125,18 +125,38 @@ export default async function ({ addon, console, msg }) {
...
+      if (iconUrl.startsWith("data:")) return "data:";
+      else return iconUrl;
+    });
+    delete externalImages["data:"];
+
+    // To help with testing this PR. Will be removed.
+    // To see  the logs, export as PNG or SVG.
+    console.log("Images (", svg.querySelectorAll("image").length, ")", Array.from(svg.querySelectorAll("image")));
+    console.log("Amount of different URLs to be fetched:", Object.keys(externalImages).length);
+
```
Comment (WorldLanguages) [inline addons/blocks2image/userscript.js:149]:
```suggestion

```

**Review by Samq64 — APPROVED** [review]

**Comment by WorldLanguages** [comment]
mxmou is busy, merging
