### PR TITLE
preview-project-description: simpler implementation

### LINKED ISSUE #6782: Remove beta tag from preview-project-description
No known bugs except #6698

### LINKED ISSUE #6884: `preview-project-description` flashes when running a project after entering and leaving the editor
### Description

When using `preview-project-description` on a project with speech bubbles, it'll flash whenever they appear.

### Steps to reproduce

1. Go to a project you made with speech bubbles
2. Enable the "Preview" toggle
3. Run the project

### Demonstration(s) and additional context

_No response_

### Environment

Browser: Edge 119
Scratch Addons version: 1.35.1
Operating system: Windows

### PR DESCRIPTION
**Pull request by mxmou**
Resolves #6884
Resolves #6782

### Changes

Changes the way `preview-project-description` works. It now overrides the `render` function of the `Preview` component, which makes the code much simpler.

### Reason for changes

Forcing the whole page to rerender after each state change is bad for performance.

### Tests

Tested on Edge and Firefox.

### CODE REVIEW

File: addons/preview-project-description/userscript.js [hunk 1]
```diff
@@ -148,77 +128,22 @@ export default async function ({ addon, console, msg }) {
...
+    const reactContainerKey = Object.keys(reactRootElement).find((key) => key.startsWith(REACT_CONTAINER_PREFIX));
+    let instance = reactRootElement[reactContainerKey];
+    while (!instance.stateNode || typeof instance.stateNode.handleUpdateProjectId !== "function") {
+      instance = instance.child;
+    }
+    const PreviewComponent = instance.stateNode.constructor;
+    const oldRender = PreviewComponent.prototype.render;
+    PreviewComponent.prototype.render = function () {
+      const oldProps = this.props;
+      this.props = { ...this.props, isEditable: !currentlyEnabled };
```
Comment (WorldLanguages) [inline addons/preview-project-description/userscript.js:143]: Excellent! Thanks mxmou

Messages from 3 months ago lol:

image

Comment (WorldLanguages) [reply addons/preview-project-description/userscript.js:143]: (the folders addon did use this pattern apparently, but I missed it!)

**Comment by WorldLanguages** [comment]
Let's also remove the beta tag from the addon (which would close #6782)

**Comment by WorldLanguages** [comment]
A small note: the remaining reference to `_saProjectDescription` can be removed, as its only usage was the now-removed statechanged event to avoid infinite loops.

**Review by WorldLanguages — APPROVED** [review]
Tested in Chromium! :)

**Comment by WorldLanguages** [comment]
https://www.youtube.com/watch?v=35Q-F9t-qLA

**Comment by mxmou** [comment]
> https://www.youtube.com/watch?v=35Q-F9t-qLA

Can repro. The error message is:
```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

The browser's translate function might be doing something weird with the DOM structure.

**Comment by WorldLanguages** [comment]
1.41.0 feedback - I cannot reproduce - only one report by 1 user

> I found a glitch with the Preview project instructions and notes + Project notes tabs.
If you enable the preview while the project tabs are on, the preview will revert the display back to normal. (Not in tabs) 

> That's bad.
Here's where it gets worse.

> If you disable the preview after that, my scratch crashes. (And this might just be me, but the back button doesn't work.)

> I hope you can fix this simple glitch.

**Comment by mxmou** [comment]
> If you disable the preview after that, my scratch crashes. (And this might just be me, but the back button doesn't work.)

I can't repro either. I also tried projects with empty instructions, notes, or both.
