### PR TITLE
Ctrl + F Fix

### LINKED ISSUE #177: Options page: focus search box when pressing Ctrl+F
...instead of browser search. If the user really wants to use browser search, they can focus the address bar, and then press Ctrl+F.
I'm creating this issue bc it should be easy to implement, and I've seen myself pressing Ctrl+F trying to focus the search box, when it's already autofocused (silly me...), and browser search doesn't work as well.

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**
**Resolves**
Resolves #177 
**Changes**

Focuses the search box when ctrl + f is clicked.

### CODE REVIEW

**Comment by NoobTracker** [comment]
That sounds like a good idea!

File: webpages/settings/index.js [hunk 1]
```diff
@@ -126,3 +126,9 @@ chrome.runtime.sendMessage("getSettingsInfo", ({ manifests, addonsEnabled, addon
 vue.$watch("selectedTab", function (newSelectedTab) {
   this.selectedTag = null;
 });
+window.addEventListener("keydown", function (e) {
+  if (e.keyCode === 114 || (e.ctrlKey && e.keyCode === 70)) {
+    e.preventDefault();
+    $("#searchBox").focus();
```
Comment (WorldLanguages) [inline webpages/settings/index.js:132]: I don't think there's jQuery in this context. This might have worked in the console because `$` is a shortcut for `document.querySelector`, but I don't think this would actually work.
