### PR TITLE
Make sure option element IDs aren't duplicated

### LINKED ISSUE #8749: Only one of repeated addon `select` settings is displayed correctly
### Description

When the same addon appears more than once in the addon list, a visual bug, regressed NOT by #8678, surprisingly, but #8577, affects how its setting values are displayed. This only seems to affect `"select"` settings, where only one occurrence of an identical option will render as highlighted. If the first one is offscreen, changing the setting also auto-scrolls the page to reveal it.

It's notable that new or updated addons always appear twice in the list.

### Steps to reproduce

1. Open the settings page.
2. Enable and change the settings of the `"Improved dragging of costumes and sounds"` addon.

### Demonstration(s) and additional context

https://github.com/user-attachments/assets/fbed56a7-4a89-4690-a05a-669abd572b20

### Environment

Browser: Edge 143
Scratch Addons version: v1.45.0-pre 751866985acdbb5dc1cf1f22e370983ffcfac03b
Operating system: Windows

### PR DESCRIPTION
**Pull request by DNin01**
Resolves #8749

This works now:

https://github.com/user-attachments/assets/f6393176-b676-4f2b-884a-62b2da6170e4

Tested in Edge 144.

### CODE REVIEW

File: webpages/settings/components/addon-setting.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ export default async function ({ template }) {
       return {
         noResetDropdown: ["table", "boolean", "select"].includes(this.setting.type),
         tableChild: this.settingPath.length > 1,
-        selectName: `${this.addon._addonId}-${this.settingPath.join("-")}`,
+        selectName: `${this.$parent.groupId}-${this.addon._addonId}-${this.settingPath.join("-")}`,
```
Comment (mxmou) [inline webpages/settings/components/addon-setting.js]: I don't think accessing the parent component's prop through `$parent` like this is a good idea. The `<addon-body>` should explicitly pass it to the `<addon-setting>` so that it's easier to see where it's used when reading the code.

Comment (DNin01) [reply webpages/settings/components/addon-setting.js]: Do you know how to do that?

Comment (mxmou) [reply webpages/settings/components/addon-setting.js]: * Add `groupId` to the `props` array near the top of this file
* Add `:group-id="groupId"` in every place where an `<addon-setting>` component is created (once in `addon-body.html` and once in `addon-setting.html`)
* You can then access it as `this.groupId`

File: webpages/settings/components/addon-setting.js [hunk 2]
```diff
@@ -80,7 +80,7 @@ export default async function ({ template }) {
         });
       },
       selectOptionId(option) {
-        return `${this.selectName}-${option.id}`;
+        return `${this.groupId}-${this.selectName}-${option.id}`;
```
Comment (mxmou) [inline webpages/settings/components/addon-setting.js]:
```suggestion
        return `${this.selectName}-${option.id}`;
```
This part isn't needed because the `selectName` already includes the `groupId`.

**Review by mxmou — APPROVED** [review]
