### PR TITLE
Fix preset migration logic edge-cases and migrate `editor-theme3` & `editor-dark-mode`

### LINKED ISSUE #5992: Add migration code for #5896 and #5931
Those 2 PRs change presets and we decided that they need a migration.

I'll also look into edge cases when migrating color settings. See https://github.com/ScratchAddons/ScratchAddons/pull/5896#discussion_r1181981293 for more info.

### PR DESCRIPTION
**Pull request by WorldLanguages**
Resolves #5992

See https://github.com/ScratchAddons/ScratchAddons/pull/5896#discussion_r1181981293 for more information about the bug this fixes.

### Changes

Converts all colors (in memory) to `#{rr}{gg}{bb}{aa}` format before comparing them.
Adds preset migrations for #5896 and #5931

TODOs:

- [x] Migrate `TurboWarp Dark` preset
- [x] Migrate `Scratch 2.0` preset
- [x] Migrate all other states. See comment https://github.com/ScratchAddons/ScratchAddons/pull/5931#issuecomment-1529426595
- [x] Test all changes carefully

### Reason for changes

See above.

### Tests

All cases tested in Chromium.

### CODE REVIEW

File: background/get-addon-settings.js [hunk 1]
```diff
@@ -5,9 +5,39 @@ import minifySettings from "../libraries/common/minify-settings.js";
  the versions separately. Current versions:
 
  - editor-dark-mode 2 (bumped in v1.23 twice)
- - editor-theme3 4 (last bumped in v1.29)
+ - editor-theme3 3 (last bumped in v1.32)
```
Comment (WorldLanguages) [inline background/get-addon-settings.js:8]: TODO: was editor-theme3 ever at version 4? Doesn't seem like it. Worth double checking.

File: background/get-addon-settings.js [hunk 2]
```diff
@@ -4,10 +4,40 @@ import minifySettings from "../libraries/common/minify-settings.js";
...
+      : hexColor.length === 4 // #{r}{g}{b}  →  #{rr}{gg}{bb}ff
+      ? `#${hexColor[1].repeat(2)}${hexColor[2].repeat(2)}${hexColor[3].repeat(2)}ff`
+      : hexColor;
+
+  // Convert both colors to #{rr}{gg}{bb}{aa}
+  const currentColorRRGGBBAA = getRRGGBBAA(currentColorLowercase);
+  const oldPresetColorRRGGBBAA = getRRGGBBAA(oldPresetLowercase);
+
+  return currentColorRRGGBBAA === oldPresetColorRRGGBBAA;
+};
```
Comment (WorldLanguages) [inline background/get-addon-settings.js:31]: @mxmou Let me know if I missed anything obvious when writing this function.
It rewrites all possible hex color formats to `#{rr}{gg}{bb}{aa}` format, so that the strings can be compared character-by-character and the strings will be equal if and only if both colors are equal.

**Review by apple502j — APPROVED** [review]

File: background/get-addon-settings.js (hunk 1 above)
Comment (WorldLanguages) [reply background/get-addon-settings.js:8]: Looks like it was never at version 4. See #5146

**Comment by WorldLanguages** [comment]
✔️ Tested all possible migrations

**Comment by WorldLanguages** [comment]
@mxmou Please tell me if you can spot any mistakes. I'll merge this soon and release v1.32.0

**Comment by mxmou** [comment]
I haven't tested this but the code looks good.
