### PR TITLE
search-my-stuff: fix bugs

### LINKED ISSUE #3784: Search bar on My Stuff breaks makes all other text inputs unusable in Firefox
### Description

Trying to type into any text input on the my stuff page other than the one the addon adds is a bad experience because the addon always steals focus. Affects Scratch's own search bar and the password input to empty the trash.

https://user-images.githubusercontent.com/33787854/141408445-e141db7d-6197-49ef-949f-e1e5dedb3150.mp4

### Environment

 - Scratch Addons 1.22
 - Firefox 94
 - Linux

Seems to only affect Firefox

### PR DESCRIPTION
**Pull request by apple502j**
Resolves #3784
Fixes errors when switching pages, etc

### CODE REVIEW

File: addons/search-my-stuff/userscript.js [hunk 1]
```diff
@@ -22,12 +22,32 @@ export default async function ({ addon, global, console, msg }) {
 
   // Keyboard shortcut for focusing search bar
   document.addEventListener("keypress", (e) => {
+    // Ignore input
+    // 1) in <input> or <textarea>
+    // 2) with Ctrl/Alt/Meta keys pressed (probably browser shortcut keys)
+    // 3) that is a space character (browser shortcut key for paging down)
+    // 4) that is not represented by one alphanumeric key code (probably special letters)
```
Comment (WorldLanguages) [inline addons/search-my-stuff/userscript.js:29]: Note that we're using keypress instead of keydown, so browsers already ignore some of these.

File: addons/search-my-stuff/addon.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "Search bar on My Stuff",
-  "description": "Allows you to search your projects, studios, and trash on the My Stuff page. Simply start typing anywhere on the page to start a search. You can also use Ctrl+Enter after searching to quickly open the top search result.",
+  "description": "Allows you to search your projects, studios, and trash on the My Stuff page. Simply start typing anywhere on the page to start a search. You can also use Ctrl+Enter (Cmd+Enter on Mac) to quickly open the top search result.",
```
Comment (WorldLanguages) [inline addons/search-my-stuff/addon.json:3]: I don't think it's necessary to change the addon description.

File: addons/search-my-stuff/userscript.js [hunk 3]
```diff
@@ -25,13 +25,15 @@ export default async function ({ addon, global, console, msg }) {
...
-    // 3) that is not represented by one alphanumeric key code (probably special letters)
+    // 3) that is a space character (browser shortcut key for paging down)
+    // 4) that is not represented by one alphanumeric key code (probably special letters)
     if (
       e.target instanceof HTMLInputElement ||
       e.target instanceof HTMLTextAreaElement ||
       e.ctrlKey ||
       e.altKey ||
       e.metaKey ||
+      e.key === " " ||
```
Comment (apple502j) [inline addons/search-my-stuff/userscript.js:36]: @lisa-wolfgang Is this just an optimization (to avoid the regex?)

Comment (lisa-wolfgang) [reply addons/search-my-stuff/userscript.js:36]: I didn't know that this Regex code matched the space character.
