### PR TITLE
Fix CSS selectors after update

### LINKED ISSUE #8799: Drag and drop images no longer works
### Description

Today I went back to scratch to do a couple of things, and when I tried to drag an image from Google and drop it into the costumes list, it wouldn't grab the image regardless of the file type (`.png`, `.jpg`, etc.).
I tried disabling and re-enabling it, reinstalling the extension, and it still doesn't work.

### Steps to reproduce

1. Start a project with the drag and drop file addon active
2. Grab any google image and drag it to the selected sprite/costume
3. Try drop it into the costume list

### Demonstration(s) and additional context

_No response_

### Environment

Browser: Google Chrome 144.0.7559.97 (Build oficial) (64 bits) (cohort: Stable)
Scratch Addons version: 1.44.4
Operating system: Windows 10 Version 22H2 (Build 19045.6466)

### LINKED ISSUE #8800: so uhh the stage on left addon just broke
### Description

so like a few minutes ago i just opened a project of mine in the editor and uhh the stage was on the right i mean i saw the hud below was still swapped just.... the workspace was back on the left

### Steps to reproduce

1.
2.
3.

### Demonstration(s) and additional context

_No response_

### Environment

Browser: 
Scratch Addons version: 
Operating system:

### LINKED ISSUE #8801: Reverse order of project controls seems to be a bit broken
### Description

The green flag and stop sign seem to be reversed when the reverse order of project controls addon is on.

### Steps to reproduce

1. Enable the Reverse order of project controls addon
2. Go to either the project page or the editor of a project
3. See error

### Demonstration(s) and additional context

It appears like this right now
Image

### Environment

Browser: Chromium Win 7 port 145.0.7600.0, Chrome 138.0.0.0, Chrome 109.0.5414.120, r3dfox 140.7 ESR (seems to also happen in vanilla though)
Scratch Addons version: v1.44.4
Operating system: Windows 7 (for 1st, 3rd, and 4th browser) and MacOS 11.3

I thought I was going insane for a second LOL

Edit: Updated to Chromium 146 from 145 on the 145 one and still happening

### LINKED ISSUE #8802: "Display stage on left side" is broken
### Description

Read title, its just about all i have to say.

### Steps to reproduce

1. Enable "Display stage on left side"
2. Go to the Editor
3. You will see that its on the right side instead

### Demonstration(s) and additional context

Image

### Environment

Browser: Chrome 143
Scratch Addons version: 1.44.4
Operating system: Windows 11 Version 24H2 (64-bit)

### PR DESCRIPTION
**Pull request by Samq64**
Resolves #8799
Resolves #8800
Resolves #8801
Resolves #8802

### Changes

Fixes some CSS selectors after a Scratch update.

### Tests

Tested on Helium.

### CODE REVIEW

**Comment by Samq64** [comment]
It may also be a good idea to wrap the pause icon in a `<button>` element for consistency with Scratch.

File: addons/drag-drop/userscript.js [hunk 1]
```diff
@@ -59,7 +59,7 @@ export default async function ({ addon, console }) {
     if (
       (el = e.target.closest('div[class*="sprite-selector_sprite-selector"]')) ||
       (el = e.target.closest('div[class*="stage-selector_stage-selector"]')) ||
-      (el = e.target.closest('div[class*="selector_wrapper"]'))
+      (el = e.target.closest('aside[class*="selector_wrapper_"]'))
```
Comment (mxmou) [inline addons/drag-drop/userscript.js]: Since specificity doesn't matter here, it's probably better not to include the element type in the selector so that it's less likely to break again in the future. Same with the `div`s above.
```suggestion
      (el = e.target.closest('[class*="selector_wrapper_"]'))
```

File: addons/drag-drop/userscript.js [hunk 2]
```diff
@@ -114,9 +114,7 @@ export default async function ({ addon, console }) {
         // Simulate clicking on the "Import" option
         contextMenu.children[0].click();
       };
-    } else if (
-      (el = e.target.closest('div[class*="question_question-input"] > input[class*="input_input-form_l9eYg"]'))
-    ) {
+    } else if ((el = e.target.closest('div[class*="question_question-input"] > input[class*="input_input-form_"]'))) {
```
Comment (mxmou) [inline addons/drag-drop/userscript.js]:
```suggestion
    } else if ((el = e.target.closest('[class*="question_question-input"] > [class*="input_input-form_"]'))) {
```

File: addons/editor-stage-left/stageleft.css [hunk 3]
```diff
@@ -23,7 +23,7 @@
   margin-right: calc(0.5rem / 2);
   margin-left: 0;
 }
-[class^="gui_flex-wrapper"] {
```
Comment (mxmou) [inline addons/editor-stage-left/stageleft.css:26]: There are still many selectors in this file and others that use `^=` instead of `*=`. I think they should all be changed (in a separate PR).

File: addons/hide-delete-button/sprites.css [hunk 4]
```diff
@@ -1,3 +1,3 @@
-div[class*="sprite-selector_sprite-wrapper_"] div[class*="delete-button_delete-button_"] {
+li[class*="sprite-selector_sprite-wrapper_"] button[class*="delete-button_delete-button_"] {
```
Comment (mxmou) [inline addons/hide-delete-button/sprites.css]: The element types in this addon's userstyles don't seem to be necessary either.

**Comment by Quilant** [comment]
why is v1.45.0 included instead of v1.44.5?

**Comment by Samq64** [comment]
@WorldLanguages Should this be backported or are you ready to ship 1.45? You mentioned there would be a new release at the end of January in #8751 but I also understand if you are busy.

**Comment by WorldLanguages** [comment]
@Samq64 Hi, I'll probably release a hotfix instead so that we can get it done faster. (web store reviews also take less time if there's less lines changed)

**Comment by DNin01** [comment]
@WorldLanguages Here are four other fixes you could release:
- #8735
- #8742
- #8660
- #8739
