### PR TITLE
Fix debugger block preview and heatmap for new Blockly

### LINKED ISSUE #8955: Debugger block preview and timing heatmap is broken
### Description
Profiling is not showing the correct block preview and locations
Image

Heatmap is entirely broken erroring with:

Image

### Steps to reproduce

1. Turn on profiling and heatmap from debugger timing addon
2. Run any code

### Demonstration(s) and additional context

_No response_

### Environment

Browser: Chrome
Scratch Addons version: v1.45
Operating system: Windows

### PR DESCRIPTION
**Pull request by Joeclinton1**
<!-- Which issue(s) does this pull request fix or resolve? If there aren't any, please submit one first unless this is a hotfix or minor string update. -->

Resolves #8955

### Changes                                                                                                                                                                                
                                                                                                                                                                                             
  Updated the debugger for the new Blockly renderer in two places:                                                                                                                           
                                                                                                                                                                                             
  - Fixed block previews in the profiler/timing table by deriving preview categories from Scratch block extensions such as colours_control, instead of relying on the removed                
    jsonData.category field.                                                                                                                                                                 
  - Fixed debugger heatmap rendering on new Blockly by replacing old internal block lookups with workspace.getBlockById(...), using current block renderer APIs, and restoring block/input   
    styling correctly when heatmap is disabled or cleared.

<img width="700" alt="image" src="https://github.com/user-attachments/assets/3c589df0-3299-40e9-8eac-5cc0f050d190" />
                                                                                                                            
                                                                                                                                                                                             
  ### Reason for changes                                                                                                                                                                     

  Scratch’s move away from scratch-blocks broke debugger assumptions in both preview rendering and heatmap coloring. The profiler preview path was still expecting old block JSON category   
  metadata, and the heatmap path was still reaching into old Blockly internals and renderer fields. These changes align the debugger with the current Scratch/Blockly behavior so previews   
  and heatmap work again.                                                                                                                                                                    
                                                                                                                                                                                             
  ### Tests                                                                                                                                                                                  
                                                                                                                                                                                             
  Tested manually in the editor with the debugger timing tab on https://scratch.mit.edu/projects/1030987979:                                                                                                                                
                                                                                                                                                                                             
  - Verified profiler block previews render again for line-by-line timing rows.                                                                                                              
  - Verified heatmap can be enabled without throwing errors.                                                                                                                                 
  - Verified heatmap can be disabled and cleared without leaving text input fields stuck in the wrong visual state.

### CODE REVIEW

File: addons/debugger/timing/HeatmapManager.js [hunk 1]
```diff
@@ -7,15 +7,19 @@ function valueToHeatmapColor(value, min = 0, max = 1) {
...
+  };
+  setFill(block.pathObject.svgPath.style);
 
   // Set text color for blocks with heatmap applied
-  const textElements = block.svgGroup_.querySelectorAll(
-    ":scope > :not(.blocklyDraggable):not([data-shapes='stack']) > text, :scope > text"
-  );
+  const textElements = block
+    .getSvgRoot()
+    .querySelectorAll(":scope > :not(.blocklyDraggable):not([data-shapes='stack']) > text, :scope > text");
```
Comment (mxmou) [inline addons/debugger/timing/HeatmapManager.js]: The `data-shapes` attribute no longer exists. That part of the selector can probably be removed.

Comment (Joeclinton1) [reply addons/debugger/timing/HeatmapManager.js]: Thanks will make this change. Please approve after I do, so this can be part of the hotfix.

Comment (Joeclinton1) [reply addons/debugger/timing/HeatmapManager.js]: Image

I was skeptical but indeed it doesn't seem to have the old bug of colouring in the procedure block label (which is why that selector existed in the first place)

Image

if you drag the block though you can get a failure though. Idk if worth fixing though, as it goes away as soon as you click something.

Comment (Joeclinton1) [reply addons/debugger/timing/HeatmapManager.js]: Ok I decided to put in the time to fix it, despite it being a minimal issue. (it's possible this isn't even due to new blockly and has always been a bug)

**Review by mxmou — APPROVED** [review]

**Review by DNin01 — APPROVED** [review]
Seems OK.
